"""initial schema

Revision ID: 22ad2b9f2a2f
Revises:
Create Date: 2025-11-13 21:24:03.551931

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22ad2b9f2a2f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("foto_perfil", sa.String(length=200), nullable=True),
        sa.Column("data_cadastro", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "cartoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=50), nullable=False),
        sa.Column("limite", sa.Float(), nullable=False),
        sa.Column("vencimento_dia", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categorias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("icone", sa.String(length=50), nullable=False),
        sa.Column("cor", sa.String(length=7), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "investimentos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("quantidade", sa.Float(), nullable=False),
        sa.Column("preco_compra", sa.Float(), nullable=False),
        sa.Column("data_compra", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parcelas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("cartao_id", sa.Integer(), nullable=True),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.Column("descricao", sa.String(length=200), nullable=True),
        sa.Column("valor", sa.Float(), nullable=False),
        sa.Column("data_vencimento", sa.DateTime(), nullable=False),
        sa.Column("pago", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cartao_id"],
            ["cartoes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categorias.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.Column("descricao", sa.String(length=200), nullable=True),
        sa.Column("valor", sa.Float(), nullable=False),
        sa.Column("data_transacao", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categorias.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transacoes")
    op.drop_table("parcelas")
    op.drop_table("investimentos")
    op.drop_table("categorias")
    op.drop_table("cartoes")
    op.drop_table("users")
    # ### end Alembic commands ###
